# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{docomo_web_mailer}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["nazoking"]
  s.date = %q{2010-11-19}
  s.description = %q{Docomo Web Mail ( http://dwmail.jp/ ) をRubyからいじることの出来るライブラリです。現在は受信のみ対応しており、送信や削除することは出来ません。 }
  s.email = %q{nazoking@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "docomo_web_mailer.gemspec",
    "lib/docomo_web_mailer.rb",
    "lib/docomo_web_mailer/convert_mail.rb",
    "test/helper.rb",
    "test/test_docomo_web_mailer.rb"
  ]
  s.homepage = %q{http://github.com/nazoking/docomo_web_mailer}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Docomo Web Mail Client}
  s.test_files = [
    "test/helper.rb",
    "test/test_docomo_web_mailer.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.1"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<mechanize>, [">= 1.0"])
      s.add_development_dependency(%q<json>, [">= 0"])
      s.add_runtime_dependency(%q<mechanize>, ["> 1.0"])
      s.add_runtime_dependency(%q<json>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<mechanize>, [">= 1.0"])
      s.add_dependency(%q<json>, [">= 0"])
      s.add_dependency(%q<mechanize>, ["> 1.0"])
      s.add_dependency(%q<json>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<mechanize>, [">= 1.0"])
    s.add_dependency(%q<json>, [">= 0"])
    s.add_dependency(%q<mechanize>, ["> 1.0"])
    s.add_dependency(%q<json>, [">= 0"])
  end
end

